# Generated by Django 4.2.3 on 2023-07-16 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_account_last_login"),
    ]

    operations = [
        migrations.RemoveField(model_name="account", name="last_login",),
    ]
